services:
  frontend1:
    build:
      context: ./lp-collect
      dockerfile: Dockerfile
    container_name: lp_collect_frontend1
    ports:
      - "3001:80"
    restart: always

  frontend2:
    build:
      context: ./YORHA_v2
      dockerfile: Dockerfile
    container_name: yorha_v2_frontend2
    ports:
      - "3002:80"
    restart: always

  frontend3:
    build:
      context: ./kid-app
      dockerfile: Dockerfile
    container_name: kid_frontend3
    ports:
      - "3003:80"
    restart: always
