server {
    listen 80;
    server_name nexgen-web.com www.nexgen-web.com;

    real_ip_header CF-Connecting-IP;
    set_real_ip_from 0.0.0.0/0;

    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # root
    location / {
        proxy_pass http://lp_collect_frontend1/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # yorha
    location /yorha/ {
        proxy_pass http://yorha_v2_frontend2/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # robokids
    location /robokids/ {
        proxy_pass http://kid_frontend3/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # the-stack-burger
    location /the-stack-burger/ {
        proxy_pass http://the_stack_burger_frontend4/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
