server {
    listen 80;
    server_name _;

    # =========================
    # /app1 → frontend1
    # =========================
    location /app1/ {
        proxy_pass http://lp_collect_frontend1/;
    }

    # =========================
    # /app2 → frontend2
    # =========================
    location /app2/ {
        proxy_pass http://yorha_v2_frontend2/;
    }

    # =========================
    # /app3 → frontend3
    # =========================
    location /app3/ {
        proxy_pass http://kid_frontend3/;
    }

    # =========================
    # /app4 → frontend4
    # =========================
    location /app4/ {
        proxy_pass http://the_stack_burger_frontend4/;
    }
}
